### ISSUE TITLE
Planes para chrome?

### ISSUE THREAD

**Issue by ppizarror** [TaconeoMental/SemanaClases#1]
Existe plan para sacar la extensión en chrome? gracias!!

**Comment by TaconeoMental** [comment]
Hola Pablo. Si, totalmente!
Actualmente se encuentra en proceso de revisión por Google. Debería estar disponible prontamente en la Chrome Web Store.

**Comment by ppizarror** [comment]
Estupendo, a penas salga la testearé 😄
